apiVersion: apps/v1
kind: Deployment
metadata:
  name: chromecast-controller
spec:
  selector:
    matchLabels:
      svc: chromecast-controller
  replicas: 1
  template:
    metadata:
      labels:
        svc: chromecast-controller
    volumes:
    - name: local-videos
      hostPath:
        path: $VIDEO_PATH
    spec:
      volumeMounts:
      - name: local-videos
        mountPath: /mnt/media
      containers:
        - name: chromecast-container
          image: $DOCKER_HUB_USERNAME/iot-control-center:chromecast-controller
          imagePullPolicy: Always
          env:
            - name: MONGO_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: iot-secrets
                  key: MONGO_DB_USERNAME
            - name: MONGO_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: iot-secrets
                  key: MONGO_DB_PASSWORD
            - name: MONGO_DB_IP
              valueFrom:
                secretKeyRef:
                  name: iot-secrets
                  key: MONGO_DB_IP
            - name: VIDEO_PATH
              valueFrom:
                secretKeyRef:
                  name: iot-secrets
                  key: VIDEO_PATH
---
apiVersion: v1
kind: Service
metadata:
  name: chromecast-controller-cluster-ip
spec:
  type: ClusterIP
  selector:
    svc: chromecast-controller
  ports:
    - port: 8000
