apiVersion: apps/v1
kind: Deployment
metadata:
  name: power-service
spec:
  selector:
    matchLabels:
      svc: power-service
  replicas: 1
  template:
    metadata:
      labels:
        svc: power-service
    spec:
      containers:
        - name: power-service-container
          image: $DOCKER_HUB_USERNAME/iot-control-center:power-service
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: MONGO_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: iot-secrets
                  key: MONGO_DB_USERNAME
            - name: MONGO_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: iot-secrets
                  key: MONGO_DB_PASSWORD
            - name: MONGO_DB_IP
              valueFrom:
                secretKeyRef:
                  name: iot-secrets
                  key: MONGO_DB_IP
---
apiVersion: v1
kind: Service
metadata:
  name: power-service-cluster-ip
spec:
  type: ClusterIP
  selector:
    svc: power-service
  ports:
    - port: 8000
