apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
spec:
  selector:
    matchLabels:
      svc: ui
  replicas: 1
  template:
    metadata:
      labels:
        svc: ui
    spec:
      containers:
        - name: ui-container
          image: $DOCKER_HUB_USERNAME/iot-control-center:ui
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ui-cluster-ip
spec:
  type: ClusterIP
  selector:
    svc: ui
  ports:
    - port: 80
